### ISSUE TITLE
Extracting all sounds (music, dialog, SFX) to a universal format such as .wav?

### ISSUE THREAD

**Issue by Polymega** [Nisto/sh2ex#1]
Hi Nisto, 

Before I begin I'd like to say that I was able to successfully unpackage SLPM-65098 using sh2ex without issue: 
http://www.crimson-ceremony.net/lostreleases/item.php?id=shgame_sh2dc-ps2-jpn1

So to begin thank you for taking the time to create this program. 

While sh2ex successfully extracted the sound data the files are in formats that can't be readily played/converted, as you know. Would you have the means and/or resources to play/convert the music/dialog/SFX from the game into a loseless format such as .wav while retaining its sample rates and channels (i.e. stereo)? 

A brief backstory to the request: 

There are a group of other talented programmers/modders out there who are improving the PC version of Silent Hill 2 making it match or better than the PS2 version in numerous ways. You can see a video of some of the fixes here:

https://www.youtube.com/watch?v=878F2cbLAXo

(An improved noise grain filter is also currently being developed and is nearing completion.) 

The two major fixes left is porting the PS2's sounds to the PC version and creating soft shadows for the PC build. 

For the audio: All versions of SH2 except for the PS2 version have compressed the audio files into a lossy, noise-induced format. This is further explained here:

https://www.youtube.com/watch?v=nna2yt1c9gI&t=403

And while this situation is less than ideal the *tone and pitches* for the audio files in the PC build have also changed during the conversion. You can hear this in action here:

https://www.youtube.com/watch?v=8E5Nt8ahZRk

Without meaning to put you on the spot your research into the sound extraction of SH2 PS2 is vital into cracking open this egg and getting all music, sounds, effects, and dialog accounted for to transpose to the PC build. Any further help would be greatly, hugely, immensely appreciated by the entire Silent Hill community. (Konami has neglected this series/us fans so it's become down to us to fix what Konami has wronged at this point.) The one thing worth noting is that the PC version includes all the bonus content so either the PS2's "Greatest Hits" or "Saigo no Uta" versions would need to be used as they also include said bonus content.

And in regards to soft shadows (unrelated but if you're curious and also excited for everything being done for the PC build): Soft shadows will probably be one of the last fixes due to the complex nature of writing new shaders and injecting/overwriting the old ones in the game but we're in the very, very, very early stages of looking in to this: 

https://github.com/elishacloud/dxwrapper/issues/6

So we're hoping that with "enhanced audio" and soft shadows for the PC build we can have a true, no-kidding, definitive HD platform for this beloved, neglected classic. 

Thank you for all the work and research you've done so far and thank you for any future help and guidance you can lend for the audio!

**Comment by Nisto** [comment]
@jdkubiak if you'd like to convert the audio files to WAV, you can do so with numerous existing tools. But it will require transcoding however, as the original formats are not lossless themselves.

The raw HD/BD/TD files that are extracted can not directly be converted or played in any existing converter/player; however, I created a PSF2 set (google it) directly from those files, which you ***can*** play (and convert) using PSF2-compatible players.

To convert all of these files, I would recommend using foobar2000, from which you can convert anything that you can play in it. Just install the PSF Decoder component from the official component page on foobar2000's site. For all the other formats, get the vgmstream component.

Hope that helps. Bye!

**Comment by elishacloud** [comment]
@Nisto, first of all, thanks for responding!  I have been working with @jdkubiak to try and port the PS2 audio to PC.

We found a couple of forums [here](https://hcs64.com/mboard/forum.php?showthread=48652) and [here](https://hcs64.com/mboard/forumlong.php?showthread=36833) where you were working on ripping the PS2 audio.  However the only file we can download is [this file](https://www.sendspace.com/file/z5q4dd) which seems to only have the music tracks not the dialog or the sound effects.  Furthermore it is missing 3 tracks (based on the included readme) and it does not seem to have any of the bonus campaign's (Born From a Wish) tracks.

As far as the dialog and the sound effects, these files where posted on dropbox but have since been removed.  See [here](https://dl.dropboxusercontent.com/u/48454461/aud/sh2/Siren%20MIDI%2BSF2.7z) for an example.  So we are unable to get any of the sound effects or the dialog that you ripped.

Can you help us get the three missing tracks, the bonus campaign's (Born From a Wish) music, the sound effects and the dialog?

Thanks!

**Comment by Nisto** [comment]
@elishacloud By sound effects, are you referring to my sample pack rip? I think it was called SH2Sounds.zip? In that case, it's mostly Dropbox's fault for the disappearance of those files. Dropbox removed the ability to share links publicly without explicitly generating links for each file, and consequently, the files could not be accessed by the public anymore, so I decided to remove the files from my account, since I also couldn't update my posts on HCS Forum (they have a 24-hour limit for editing posts).

Yes, as mentioned in the readme for the gamerip, I did not include the stated tracks because they contain dialogues (which is not relevant to *music* rips). If you want those tracks, the first one is in the movie (.PSS) files (which sh2ex extracts), and the other two are from the dialogue (.SVAG) files (which sh2ex also extracts). The former can be ripped by demultiplexing the movie files using e.g. VGMToolbox, and the latter are readily playable/convert-able with foobar2000 (again, you need the vgmstream component also). But you'll have to look around for the exact PSS/SVAG files - I can't remember off the top of my head.

I think it's better for posterity's sake if people just learned how to rip these files instead of me uploading and potentially having dead links floating around over and over. It's really not very hard compared to making PSF2 rips. And you might learn a new thing or two.

Apart from that, can you name the specific files (names) you are interested in?

You can reply on HCS Forum; I think it's better to do so there.

**Comment by Polymega** [comment]
Thank you for the information @Nisto ; I've responded to you at the HCS Forums here: 
https://hcs64.com/mboard/forumlong.php?showthread=36833&lastpage 

Regards
