### ISSUE TITLE
PIC.MGF extraction

### ISSUE THREAD

**Issue by Bigmanjapan** [Nisto/sh2ex#3]
Hello Nisto. 

Recently a user stated that your script doesn't extract all textures from the PIC.MGF file. 
Apparently his script does: https://gist.github.com/infval/b23380076d77341ccc379a62ef9f23b3

Maybe you'd be interested.

**Comment by Nisto** [comment]
@Bigmanjapan I appreciate sharing the script, however, please note that this script intends to extract only data as referenced by the game's internal metadata. If there is some data not being extracted, it may simply be unused (unreferenced), which is not uncommon. For now I am closing this issue, but if you believe some data is being missed due to incorrect metadata in the script, or missing metadata from the game itself, feel free to give me another poke.
